-- Revert pipeline tables

DROP VIEW IF EXISTS pipeline_run_history;
DROP VIEW IF EXISTS active_pipeline_runs;

DROP TABLE IF EXISTS pipeline_runs;
DROP TABLE IF EXISTS pipelines;

DROP TYPE IF EXISTS PIPELINE_TRIGGER_TYPE;
DROP TYPE IF EXISTS PIPELINE_RUN_STATUS;
DROP TYPE IF EXISTS PIPELINE_STATUS;
