//! Retention sweeps for nullable blob-pointer columns.
//!
//! Several ledger rows carry a nullable blob pointer whose bytes are reclaimed on
//! the blob's own retention while the row itself is kept: a detection's enrichment
//! intermediate and its base-analysis (audit) findings, and a redaction's
//! review-analysis findings. Each is reclaimed the same way — find the rows whose
//! pointed-at blob has passed its retention window, null the pointer, and drop the
//! reference so the blob reaper can purge the bytes.
//!
//! That one shape is generated by [`clear_expired_blob_pointer`] for each
//! `(table, column)`, so the concurrency-safe null-then-guarded-decrement is
//! written once rather than copied per column.

use diesel::dsl::now;
use diesel::prelude::*;
use diesel_async::{AsyncConnection, RunQueryDsl};
use uuid::Uuid;

use crate::query::WorkspaceBlobRepository;
use crate::{Error, PgConnection, Result};

/// Generates a `clear_expired_*` sweep for one nullable blob-pointer column.
///
/// The generated function reclaims up to `limit` rows whose pointed-at blob has
/// passed its retention window: it nulls the pointer (keeping the row) and drops
/// the blob reference, so the reaper's Expire sweep can then purge the bytes.
/// Rows are locked `FOR UPDATE SKIP LOCKED`, the pointer is nulled only while it
/// still holds the selected blob, and the reference is dropped only when the null
/// actually took — so a concurrent sweep never double-drops. Returns how many were
/// cleared. Runs in one transaction so the null and the drop commit together.
macro_rules! clear_expired_blob_pointer {
    ($(#[$meta:meta])* $vis:vis fn $name:ident on $table:ident . $column:ident) => {
        $(#[$meta])*
        ///
        /// # Errors
        ///
        /// A database error if the sweep or a reference drop fails.
        $vis async fn $name(conn: &mut PgConnection, limit: i64) -> Result<usize> {
            use crate::schema::{workspace_blobs, $table};

            conn.transaction(async |conn| {
                let expired: Vec<(Uuid, Uuid)> = $table::table
                    .inner_join(
                        workspace_blobs::table
                            .on($table::$column.eq(workspace_blobs::id.nullable())),
                    )
                    .filter(workspace_blobs::expires_at.is_not_null())
                    .filter(workspace_blobs::expires_at.lt(now))
                    .filter(workspace_blobs::purged_at.is_null())
                    .limit(limit)
                    .select(($table::id, workspace_blobs::id))
                    .for_update()
                    .skip_locked()
                    .load(conn)
                    .await
                    .map_err(Error::from)?;

                let mut dropped = 0usize;
                for (row_id, blob_id) in &expired {
                    let cleared = diesel::update(
                        $table::table
                            .filter($table::id.eq(row_id))
                            .filter($table::$column.eq(blob_id)),
                    )
                    .set($table::$column.eq(None::<Uuid>))
                    .execute(conn)
                    .await
                    .map_err(Error::from)?;
                    if cleared == 1 {
                        conn.decrement_ref(*blob_id).await?;
                        dropped += 1;
                    }
                }

                Ok(dropped)
            })
            .await
        }
    };
}

clear_expired_blob_pointer! {
    /// Reclaims detections' expired enrichment-intermediate bytes.
    pub fn clear_expired_detection_intermediates on workspace_detections.intermediate_blob_id
}

clear_expired_blob_pointer! {
    /// Reclaims detections' expired base-analysis (audit) bytes.
    pub fn clear_expired_detection_audits on workspace_detections.audit_blob_id
}

clear_expired_blob_pointer! {
    /// Reclaims redactions' expired review-analysis bytes.
    pub fn clear_expired_review_audits on workspace_redactions.review_audit_blob_id
}

#[cfg(test)]
mod tests {
    use jiff::{Span, Timestamp};

    use super::*;
    use crate::model::{NewBlob, NewWorkspaceDetection, NewWorkspaceRedaction};
    use crate::query::{
        WorkspaceBlobRepository, WorkspaceDetectionRepository, WorkspaceRedactionRepository,
    };
    use crate::test_util::{TestDatabase, backdate};

    #[tokio::test]
    async fn clearing_a_detection_audit_keeps_the_row_and_nulls_the_pointer() -> anyhow::Result<()>
    {
        use crate::schema::workspace_detections::{self, dsl};

        let db = TestDatabase::start().await;
        let seeded = db.seed_pipeline_and_document().await;
        let mut conn = db.client.get_connection().await?;

        let detection = conn
            .create_workspace_detection(NewWorkspaceDetection::test(
                seeded.workspace_id,
                seeded.pipeline_id,
                seeded.account_id,
                seeded.document_id,
            ))
            .await?;

        // Attach a base-analysis blob (records the reference), then point the
        // detection at it — mirroring what finalize does.
        let mut new_blob = NewBlob::test(seeded.workspace_id);
        new_blob.expires_at = Some((Timestamp::now() + Span::new().hours(1)).into());
        let blob = conn.find_or_create_blob(new_blob).await?;
        diesel::update(workspace_detections::table.filter(dsl::id.eq(detection.id)))
            .set(dsl::audit_blob_id.eq(Some(blob.id)))
            .execute(&mut conn)
            .await?;
        backdate::blob_span(
            &mut conn,
            blob.id,
            Timestamp::now() - Span::new().hours(2),
            Timestamp::now() - Span::new().hours(1),
        )
        .await?;

        let cleared = clear_expired_detection_audits(&mut conn, 50).await?;
        assert_eq!(cleared, 1);

        // The detection row survives (a ledger record); its pointer is nulled and
        // the blob reference dropped so the reaper can reclaim the bytes.
        let (kept, _) = conn
            .find_workspace_detection_by_id(seeded.workspace_id, detection.id)
            .await?
            .expect("detection row survives");
        assert!(kept.audit_blob_id.is_none(), "the audit pointer is nulled");
        assert_eq!(conn.find_blob_by_id(blob.id).await?.unwrap().ref_count, 0);
        Ok(())
    }

    #[tokio::test]
    async fn clearing_a_review_audit_keeps_the_row_and_nulls_the_pointer() -> anyhow::Result<()> {
        let db = TestDatabase::start().await;
        let seeded = db.seed_pipeline_and_document().await;
        let mut conn = db.client.get_connection().await?;

        let detection = conn
            .create_workspace_detection(NewWorkspaceDetection::test(
                seeded.workspace_id,
                seeded.pipeline_id,
                seeded.account_id,
                seeded.document_id,
            ))
            .await?;
        let mut new_blob = NewBlob::test(seeded.workspace_id);
        new_blob.expires_at = Some((Timestamp::now() + Span::new().hours(1)).into());
        let blob = conn.find_or_create_blob(new_blob).await?;
        let redaction = conn
            .create_redaction(NewWorkspaceRedaction {
                detection_id: detection.id,
                account_id: seeded.account_id,
                output_document_id: None,
                review_audit_blob_id: Some(blob.id),
            })
            .await?;
        backdate::blob_span(
            &mut conn,
            blob.id,
            Timestamp::now() - Span::new().hours(2),
            Timestamp::now() - Span::new().hours(1),
        )
        .await?;

        let cleared = clear_expired_review_audits(&mut conn, 50).await?;
        assert_eq!(cleared, 1);

        let kept = conn
            .find_redaction_in_workspace(seeded.workspace_id, redaction.id)
            .await?
            .expect("redaction row survives");
        assert!(
            kept.review_audit_blob_id.is_none(),
            "the review-audit pointer is nulled"
        );
        assert_eq!(conn.find_blob_by_id(blob.id).await?.unwrap().ref_count, 0);
        Ok(())
    }
}
