//! Chunk transformer configuration.

use serde::{Deserialize, Serialize};

/// Configuration for chunking content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChunkConfig {
    /// Chunking strategy.
    #[serde(flatten)]
    pub chunk_strategy: ChunkStrategy,

    /// Whether to use LLM-powered contextual chunking.
    ///
    /// When enabled, each chunk will include additional context
    /// generated by an LLM to improve retrieval quality.
    #[serde(default)]
    pub contextual_chunking: bool,
}

/// Chunking strategy.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "chunk_strategy", rename_all = "snake_case")]
pub enum ChunkStrategy {
    /// Chunk by character count.
    Character {
        /// Maximum chunk size in characters.
        max_characters: u32,
        /// Overlap between chunks in characters.
        overlap_characters: u32,
    },
    /// Chunk by page boundaries.
    Page {
        /// Overlap between chunks in pages.
        overlap_pages: u32,
    },
    /// Chunk by document sections/headings.
    Section {
        /// Minimum chunk size in characters.
        min_characters: u32,
        /// Maximum chunk size in characters.
        max_characters: u32,
        /// Overlap between chunks in characters.
        overlap_characters: u32,
    },
    /// Chunk by semantic similarity.
    Similarity {
        /// Maximum chunk size in characters.
        max_characters: u32,
        /// Similarity score threshold (0.0 to 1.0).
        score: f32,
    },
}
