name: "Setup NATS"
description: "Sets up NATS server and waits for it to be ready"
author: "nvisy"

inputs:
  nats-host:
    description: "NATS host"
    required: false
    default: "localhost"
  nats-port:
    description: "NATS port"
    required: false
    default: "4222"
  nats-timeout:
    description: "Timeout in seconds to wait for NATS"
    required: false
    default: "30"
  working-directory:
    description: "Working directory relative to repository root"
    required: false
    default: "."

outputs:
  nats-ready:
    description: "Whether NATS is ready and accessible"
    value: ${{ steps.wait-nats.outputs.ready }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if ! [[ "${{ inputs.nats-timeout }}" =~ ^[0-9]+$ ]]; then
          echo "Error: nats-timeout must be a number"
          exit 1
        fi
        if ! [[ "${{ inputs.nats-port }}" =~ ^[0-9]+$ ]]; then
          echo "Error: nats-port must be a number"
          exit 1
        fi

    - name: Set environment variables
      shell: bash
      run: |
        echo "NATS_HOST=${{ inputs.nats-host }}" >> $GITHUB_ENV
        echo "NATS_PORT=${{ inputs.nats-port }}" >> $GITHUB_ENV
        echo "NATS_TIMEOUT=${{ inputs.nats-timeout }}" >> $GITHUB_ENV

    - name: Install NATS CLI
      shell: bash
      run: |
        case "$RUNNER_OS" in
          Linux)
            wget -O nats.tar.gz https://github.com/nats-io/natscli/releases/latest/download/nats-*-linux-amd64.tar.gz
            tar -xzf nats.tar.gz
            sudo mv nats-*-linux-amd64/nats /usr/local/bin/
            ;;
          macOS)
            if command -v brew >/dev/null 2>&1; then
              brew install nats-io/nats-tools/nats
            fi
            ;;
          Windows)
            curl -L -o nats.zip https://github.com/nats-io/natscli/releases/latest/download/nats-*-windows-amd64.zip
            unzip nats.zip
            echo "$(pwd)/nats-*-windows-amd64" >> $GITHUB_PATH
            ;;
        esac

    - name: Wait for NATS
      id: wait-nats
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        chmod +x scripts/wait-for-nats.sh
        if scripts/wait-for-nats.sh; then
          echo "ready=true" >> $GITHUB_OUTPUT
        else
          echo "ready=false" >> $GITHUB_OUTPUT
          exit 1
        fi

branding:
  icon: "message-circle"
  color: "blue"
