//! Permission-checked workspace extractor.
//!
//! [`Authorized<P>`] resolves the addressed workspace and enforces the required
//! permission `P` before the handler body runs, so a handler declares its
//! authorization in its signature rather than repeating a
//! `get_connection` + `authorize_workspace` block. The permission is a marker
//! type (one per `Permission`, generated by the `authz_permissions!` macro
//! below); the extractor yields the resolved [`Workspace`] and, for a member
//! (i.e. not a global admin), their [`WorkspaceMember`].

use std::marker::PhantomData;

use aide::OperationInput;
use aide::generate::GenContext;
use aide::openapi::{Operation, Response};
use axum::extract::FromRequestParts;
use axum::http::request::Parts;
use nvisy_postgres::model::{Workspace, WorkspaceMember};
use uuid::Uuid;

use super::{AuthProvider, AuthState, Permission};
use crate::extract::{PgPool, WorkspaceContext};
use crate::handler::Error;

/// A workspace permission required by a handler, expressed as a marker type so it
/// can parameterize [`Authorized`]. Implemented for one zero-sized type per
/// [`Permission`] by the `authz_permissions!` macro.
pub trait RequiredPermission {
    /// The permission this marker stands for.
    const PERMISSION: Permission;
}

/// Proof that the caller holds permission `P` in the addressed workspace.
///
/// Extracting `Authorized<P>` resolves the `{workspaceSlug}` path segment to a
/// live [`Workspace`] and authorizes the caller for `P::PERMISSION`, rejecting
/// with `403 Forbidden` otherwise (and `404` for an unknown workspace, `401` for
/// a bad token) — exactly the checks a handler used to run by hand. The handler
/// receives the resolved workspace and the caller's membership.
#[must_use]
pub struct Authorized<P: RequiredPermission> {
    /// The authenticated caller's account id.
    pub account_id: Uuid,
    /// The workspace the `{workspaceSlug}` segment resolved to.
    pub workspace: Workspace,
    /// The caller's membership in the workspace, or `None` for a global admin
    /// (who is authorized without being a member).
    pub member: Option<WorkspaceMember>,
    _permission: PhantomData<P>,
}

impl<P, S> FromRequestParts<S> for Authorized<P>
where
    P: RequiredPermission,
    S: Sync + Send + 'static,
    AuthState: FromRequestParts<S, Rejection = Error<'static>>,
    WorkspaceContext: FromRequestParts<S, Rejection = Error<'static>>,
    PgPool: FromRequestParts<S, Rejection = Error<'static>>,
{
    type Rejection = Error<'static>;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        // Each collaborator resolves independently: AuthState verifies the token
        // (cached in extensions), WorkspaceContext resolves the slug, PgPool hands
        // us a pooled connection for the membership/role check.
        let auth = AuthState::from_request_parts(parts, state).await?;
        let WorkspaceContext(workspace) =
            WorkspaceContext::from_request_parts(parts, state).await?;
        let PgPool(mut conn) = PgPool::from_request_parts(parts, state).await?;

        let account_id = auth.account_id();
        let member = auth
            .authorize_workspace(&mut conn, workspace.id, P::PERMISSION)
            .await?;

        Ok(Self {
            account_id,
            workspace,
            member,
            _permission: PhantomData,
        })
    }
}

impl<P: RequiredPermission> OperationInput for Authorized<P> {
    fn operation_input(ctx: &mut GenContext, operation: &mut Operation) {
        // Same OpenAPI surface as extracting AuthState + WorkspaceContext by hand:
        // the bearer security scheme and the {workspaceSlug} path parameter.
        <AuthState>::operation_input(ctx, operation);
        WorkspaceContext::operation_input(ctx, operation);
    }

    fn inferred_early_responses(
        ctx: &mut GenContext,
        operation: &mut Operation,
    ) -> Vec<(Option<aide::openapi::StatusCode>, Response)> {
        WorkspaceContext::inferred_early_responses(ctx, operation)
    }
}

/// Defines a [`RequiredPermission`] marker type per [`Permission`], for use as
/// the `P` in [`Authorized<P>`].
macro_rules! authz_permissions {
    ($($marker:ident => $permission:expr),+ $(,)?) => {
        $(
            #[doc = concat!("Marker for [`Permission::", stringify!($marker), "`] as an [`Authorized`] parameter.")]
            pub struct $marker;

            impl RequiredPermission for $marker {
                const PERMISSION: Permission = $permission;
            }
        )+
    };
}

authz_permissions! {
    ViewWorkspace => Permission::ViewWorkspace,
    UpdateWorkspace => Permission::UpdateWorkspace,
    DeleteWorkspace => Permission::DeleteWorkspace,
    ViewFiles => Permission::ViewFiles,
    UploadFiles => Permission::UploadFiles,
    UpdateFiles => Permission::UpdateFiles,
    DownloadOriginalFiles => Permission::DownloadOriginalFiles,
    DownloadRedactedFiles => Permission::DownloadRedactedFiles,
    DownloadAudit => Permission::DownloadAudit,
    DeleteFiles => Permission::DeleteFiles,
    ViewPipelines => Permission::ViewPipelines,
    CreatePipelines => Permission::CreatePipelines,
    UpdatePipelines => Permission::UpdatePipelines,
    DeletePipelines => Permission::DeletePipelines,
    ViewDetections => Permission::ViewDetections,
    RunDetections => Permission::RunDetections,
    RunRedactions => Permission::RunRedactions,
    ViewAnalytics => Permission::ViewAnalytics,
    ViewActivity => Permission::ViewActivity,
    UseChat => Permission::UseChat,
    ViewMembers => Permission::ViewMembers,
    InviteMembers => Permission::InviteMembers,
    RemoveMembers => Permission::RemoveMembers,
    ManageRoles => Permission::ManageRoles,
    ViewConnections => Permission::ViewConnections,
    ManageConnections => Permission::ManageConnections,
    RunConnectionSyncs => Permission::RunConnectionSyncs,
    ViewProviders => Permission::ViewProviders,
    ManageProviders => Permission::ManageProviders,
    ViewPolicies => Permission::ViewPolicies,
    ManagePolicies => Permission::ManagePolicies,
    ViewWebhooks => Permission::ViewWebhooks,
    CreateWebhooks => Permission::CreateWebhooks,
    UpdateWebhooks => Permission::UpdateWebhooks,
    DeleteWebhooks => Permission::DeleteWebhooks,
    TestWebhooks => Permission::TestWebhooks,
}
