//! Request extractors with improved error handling and validation.
//!
//! This module provides a comprehensive suite of custom Axum extractors that enhance
//! the default functionality with better error messages, validation, logging, and
//! type safety. All extractors are designed to be drop-in replacements for their
//! standard Axum counterparts while providing additional features.

mod auth;
mod avatar_upload;
mod idempotency_key;
mod reject;
mod security_context;
mod typed_header;
mod valid;
mod version;
mod workspace_context;

// Glob: the auth surface includes the permission markers (one per `Permission`,
// generated by a macro) used as `Authorized<P>`, alongside the named types.
pub use crate::extract::auth::*;
pub use crate::extract::avatar_upload::AvatarUpload;
pub use crate::extract::idempotency_key::IdempotencyKey;
pub use crate::extract::reject::{Form, Json, Multipart, Path, Query};
pub use crate::extract::security_context::SecurityContext;
pub use crate::extract::typed_header::TypedHeader;
pub use crate::extract::valid::{ValidateJson, validators};
pub use crate::extract::version::Version;
pub use crate::extract::workspace_context::WorkspaceContext;
