//! File source enumeration indicating how a file was created.

use diesel_derive_enum::DbEnum;
#[cfg(feature = "schema")]
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use strum::{Display, EnumIter, EnumString};

/// Defines how a file was created in the system.
///
/// This enumeration corresponds to the `FILE_SOURCE` PostgreSQL enum and is used
/// to track the origin of files - whether they were uploaded by users, imported
/// from external sources, or generated by the system.
#[derive(Debug, Default, Clone, Copy, Eq, PartialEq)]
#[cfg_attr(feature = "schema", derive(JsonSchema))]
#[derive(Serialize, Deserialize, DbEnum, Display, EnumIter, EnumString)]
#[ExistingTypePath = "crate::schema::sql_types::FileSource"]
pub enum FileSource {
    /// File was manually uploaded by a user
    #[db_rename = "uploaded"]
    #[serde(rename = "uploaded")]
    #[default]
    Uploaded,

    /// File was imported from an external source
    #[db_rename = "imported"]
    #[serde(rename = "imported")]
    Imported,

    /// File was generated by the system
    #[db_rename = "generated"]
    #[serde(rename = "generated")]
    Generated,
}

impl FileSource {
    /// Returns whether the file was uploaded by a user.
    #[inline]
    pub fn is_uploaded(self) -> bool {
        matches!(self, FileSource::Uploaded)
    }

    /// Returns whether the file was imported from an external source.
    #[inline]
    pub fn is_imported(self) -> bool {
        matches!(self, FileSource::Imported)
    }

    /// Returns whether the file was generated by the system.
    #[inline]
    pub fn is_generated(self) -> bool {
        matches!(self, FileSource::Generated)
    }

    /// Returns whether the file was created by a user action (uploaded or imported).
    #[inline]
    pub fn is_user_created(self) -> bool {
        matches!(self, FileSource::Uploaded | FileSource::Imported)
    }

    /// Returns whether the file was created automatically (generated).
    #[inline]
    pub fn is_system_created(self) -> bool {
        matches!(self, FileSource::Generated)
    }
}
